### ISSUE TITLE
恭喜!

### ISSUE THREAD

**Issue by mkoplm777** [programthink/sites#2]
可惜不能匿名交流，不爽啊
里不FQ，居然进不了？

**Comment by gongmincn** [comment]
不用吧！

**Comment by gongmincn** [comment]
我没有翻墙啊！

**Comment by programthink** [comment]
TO mkoplm777
GitHub 不支持匿名评论，俺也没办法 :(

其实捏，
可以单独注册一个 GitHub 帐号，并确保该帐号与自己的其它帐号毫无关联。
然后始终采用双重代理操作该帐号。
如此一来，效果跟“匿名”是类似的
