### ISSUE TITLE
站点推荐

### ISSUE THREAD

**Issue by careux** [programthink/sites#3]
我觉得可以把**自由微博** [https://freeweibo.com/](https://freeweibo.com/) 加进**新闻聚合类**去嘛，通过它基本上能快速了解国内近期发生的事情（而且，FreeWeibo跟GreatFire也是同一“小撮”人建的，人家以前还给你的Blog做了免翻墙镜像呢，来而不往非礼也嘛）。另外，我感觉GitHub虽然近来很火，但是开源项目貌似还没多少沉淀，而且大多数项目质量其实不高（可能人家本来就没想正式发布，只是免费账户只能建公共仓库），所以，我觉得可以加一个**CodeProject** [http://www.codeproject.com/](http://www.codeproject.com/) 到**开源项目集散地**里作为补充（话说SourceForge前段时间捆绑软件到开源项目，名声搞得很不好呀，哎，可惜了）。

哈哈，其实我只是过来冒一个泡而已:blush:

**Comment by maximusfxb** [comment]
Congratulations

**Comment by programthink** [comment]
TO careux
感谢你的反馈 :)
在本项目中，你是第一个正经反馈的网友。（前面几个 issue 都是灌水）
刚才已经把“自由微博”和“Code Proect”加入 wiki 页面
